package com.example.readeasy.Business.beans;

public enum TipoFornecedor {
    EDITORA, ESCRITOR_INDEPENDENTE, DOADOR_ANONIMO,
    INSTITUICAO_PUBLIC, INSTITUICAO_PRIVADA, DISTRIBUIDORA_DE_LIVRO, ATACADISTAS;
}
